name: Publish to npm on tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Verify package.json version matches tag
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Tag: $TAG"
          echo "package.json version: $PKG_VERSION"
          if [ "$PKG_VERSION" != "$TAG" ]; then
            echo "ERROR: package.json version ($PKG_VERSION) does not match tag ($TAG)."
            echo "Bump version locally (npm version $TAG --no-git-tag-version), commit, push, and re-tag."
            exit 1
          fi

      - name: Install deps (no scripts)
        run: |
          npm ci --ignore-scripts || npm i --ignore-scripts

      - name: "Optional: npm pkg fix"
        run: |
          npm pkg fix || true

      - name: Publish to npm (with provenance)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public --provenance
